{% set name = "birdsong-recognition-dataset" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/birdsong-recognition-dataset-{{ version }}.tar.gz
  sha256: 7d15bccb7cb5e767f1f4a5b308c6b568ffb3e5a6822b4831f0cbc46873d0f321

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - flit-core
  run:
    - numpy >=1.18.1
    - python >=3.7

test:
  imports:
    - birdsongrec
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/birdsong-recognition-dataset/
  summary: 'Functions for working with this data repository: https://figshare.com/articles/BirdsongRecognition/3470165'
  dev_url: https://github.com/NickleDave/koumura
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NickleDave
